# Generated by Django 4.0.1 on 2022-01-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
